os:
  - osx

language: node_js

node_js:
 - "8"

before_install:
 - brew update
 - brew install wine

script:
  - node --version
  - npm --version
  - npm install
  - npm run releaseml

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
