environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install 7zip-bin-win

build_script:
  - node --version
  - npm --version
  - npm run releasew
